# MATH 210 Introduction to Mathematical Computing

**April 10, 2024**

In [36]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

## Diagonalization

A matrix is diagonalizable if there exists an invertible matrix $P$ and diagonal matrix $D$ such that $A = PDP^{-1}$. A matrix is diagonalization if and only if it has $n$ linearly independent eigenvectors.

In [37]:
A = np.array([[1.,-1.,0.],[-1.,2.,-1],[0.,-1.,1.]])
A

array([[ 1., -1.,  0.],
       [-1.,  2., -1.],
       [ 0., -1.,  1.]])

In [38]:
evals,evecs = la.eig(A)

In [39]:
evals

array([ 3.00000000e+00+0.j,  1.00000000e+00+0.j, -5.13860489e-17+0.j])

In [40]:
P = evecs
P

array([[-4.08248290e-01, -7.07106781e-01,  5.77350269e-01],
       [ 8.16496581e-01,  2.48915666e-16,  5.77350269e-01],
       [-4.08248290e-01,  7.07106781e-01,  5.77350269e-01]])

In [41]:
D = np.diag(evals.real)
D

array([[ 3.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00, -5.13860489e-17]])

In [42]:
result = P@D@la.inv(P)

In [43]:
result.round(2)

array([[ 1., -1., -0.],
       [-1.,  2., -1.],
       [-0., -1.,  1.]])

## Computing Matrix Powers

$A^k = P D^k P^{-1}$

In [44]:
A@A@A@A

array([[ 14., -27.,  13.],
       [-27.,  54., -27.],
       [ 13., -27.,  14.]])

In [45]:
Pinv = la.inv(P)

In [46]:
P@D**4@Pinv

array([[ 14., -27.,  13.],
       [-27.,  54., -27.],
       [ 13., -27.,  14.]])

## Power Method

In [47]:
A

array([[ 1., -1.,  0.],
       [-1.,  2., -1.],
       [ 0., -1.,  1.]])

In [48]:
x0 = np.array([1.,3.,-2.])

In [50]:
N = 20
xk = x0
for k in range(N):
    xk = A@xk
    print(xk)

[-2.  7. -5.]
[ -9.  21. -12.]
[-30.  63. -33.]
[-93. 189. -96.]
[-282.  567. -285.]
[-849. 1701. -852.]
[-2550.  5103. -2553.]
[-7653. 15309. -7656.]
[-22962.  45927. -22965.]
[-68889. 137781. -68892.]
[-206670.  413343. -206673.]
[-620013. 1240029. -620016.]
[-1860042.  3720087. -1860045.]
[-5580129. 11160261. -5580132.]
[-16740390.  33480783. -16740393.]
[-5.02211730e+07  1.00442349e+08 -5.02211760e+07]
[-1.50663522e+08  3.01327047e+08 -1.50663525e+08]
[-4.51990569e+08  9.03981141e+08 -4.51990572e+08]
[-1.35597171e+09  2.71194342e+09 -1.35597171e+09]
[-4.06791513e+09  8.13583027e+09 -4.06791514e+09]


In [51]:
xk/xk[0]

array([ 1., -2.,  1.])

In [52]:
xk/np.max(np.abs(xk))

array([-0.5,  1. , -0.5])

In [53]:
xk/la.norm(xk)

array([-0.40824829,  0.81649658, -0.40824829])

In [54]:
N = 20
xk = x0
for k in range(N):
    xk = A@xk
    xk = xk/xk[0]
    print(xk)

[ 1.  -3.5  2.5]
[ 1.         -2.33333333  1.33333333]
[ 1.  -2.1  1.1]
[ 1.         -2.03225806  1.03225806]
[ 1.        -2.0106383  1.0106383]
[ 1.         -2.00353357  1.00353357]
[ 1.         -2.00117647  1.00117647]
[ 1.       -2.000392  1.000392]
[ 1.         -2.00013065  1.00013065]
[ 1.         -2.00004355  1.00004355]
[ 1.         -2.00001452  1.00001452]
[ 1.         -2.00000484  1.00000484]
[ 1.         -2.00000161  1.00000161]
[ 1.         -2.00000054  1.00000054]
[ 1.         -2.00000018  1.00000018]
[ 1.         -2.00000006  1.00000006]
[ 1.         -2.00000002  1.00000002]
[ 1.         -2.00000001  1.00000001]
[ 1. -2.  1.]
[ 1. -2.  1.]


In [56]:
N = 20
xk = x0
for k in range(N):
    xk = A@xk
    xk = xk/np.max(np.abs(xk))
    print(xk)

[-0.28571429  1.         -0.71428571]
[-0.42857143  1.         -0.57142857]
[-0.47619048  1.         -0.52380952]
[-0.49206349  1.         -0.50793651]
[-0.4973545  1.        -0.5026455]
[-0.49911817  1.         -0.50088183]
[-0.49970606  1.         -0.50029394]
[-0.49990202  1.         -0.50009798]
[-0.49996734  1.         -0.50003266]
[-0.49998911  1.         -0.50001089]
[-0.49999637  1.         -0.50000363]
[-0.49999879  1.         -0.50000121]
[-0.4999996  1.        -0.5000004]
[-0.49999987  1.         -0.50000013]
[-0.49999996  1.         -0.50000004]
[-0.49999999  1.         -0.50000001]
[-0.5  1.  -0.5]
[-0.5  1.  -0.5]
[-0.5  1.  -0.5]
[-0.5  1.  -0.5]


In [57]:
N = 20
xk = x0
for k in range(N):
    xk = A@xk
    xk = xk/la.norm(xk)
    print(xk)

[-0.22645541  0.79259392 -0.56613852]
[-0.34874292  0.81373347 -0.46499055]
[-0.38866104  0.81618818 -0.42752714]
[-0.40175129  0.8164623  -0.41471101]
[-0.40608635  0.81649277 -0.41040642]
[-0.40752806  0.81649616 -0.40896809]
[-0.40800826  0.81649653 -0.40848827]
[-0.40816829  0.81649658 -0.40832829]
[-0.40822162  0.81649658 -0.40827496]
[-0.4082394   0.81649658 -0.40825718]
[-0.40824533  0.81649658 -0.40825125]
[-0.4082473   0.81649658 -0.40824928]
[-0.40824796  0.81649658 -0.40824862]
[-0.40824818  0.81649658 -0.4082484 ]
[-0.40824825  0.81649658 -0.40824833]
[-0.40824828  0.81649658 -0.4082483 ]
[-0.40824829  0.81649658 -0.40824829]
[-0.40824829  0.81649658 -0.40824829]
[-0.40824829  0.81649658 -0.40824829]
[-0.40824829  0.81649658 -0.40824829]


In [58]:
xk@A@xk/(xk@xk)

3.0000000000000004

In [59]:
A = np.array([[1.,2.],[2.,1.]])
N = 20
xk = np.array([2.,3.])
for k in range(N):
    xk = A@xk
    xk = xk/xk[0]
    print(xk)

[1.    0.875]
[1.         1.04545455]
[1.         0.98529412]
[1.        1.0049505]
[1.         0.99835526]
[1.         1.00054885]
[1.         0.99981712]
[1.         1.00006097]
[1.         0.99997968]
[1.         1.00000677]
[1.         0.99999774]
[1.         1.00000075]
[1.         0.99999975]
[1.         1.00000008]
[1.         0.99999997]
[1.         1.00000001]
[1. 1.]
[1. 1.]
[1. 1.]
[1. 1.]
