# MATH 210 Introduction to Mathematical Computing

**April 8, 2024**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

## Eigenvalues and Eigenvectors

In [2]:
A = np.array([[1.,2.],[2.,1.]])
A

array([[1., 2.],
       [2., 1.]])

The function `la.eig` returns a tuple.

In [3]:
result = la.eig(A)

In [4]:
type(result)

tuple

The first entry is the array of eigenvalues.

In [5]:
result[0]

array([ 3.+0.j, -1.+0.j])

The second entry is the matrix of eigenvectors.

In [6]:
result[1]

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

We can unpack the arrays directly from `la.eig`:

In [7]:
evals,evecs = la.eig(A)

The function `la.eig` always returns the array of eigenvalues as complex numbers.

In [8]:
evals

array([ 3.+0.j, -1.+0.j])

If we know the eigenvalues are real (ie. when $A$ is symmetric) then use `np.real` to get the real part.

In [9]:
evals = np.real(evals)
evals

array([ 3., -1.])

The function `la.eig` always returns the array of eigenvectors `evecs` as **unit** vectors with eigenvector $\mathbf{v}_i$ in column $i$ for eigenvalue $\lambda_i$ in `evals`.

In [10]:
evecs

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [11]:
A = np.array([[1.,-1.,0.],[-1.,2.,-1],[0.,-1.,1.]])
A

array([[ 1., -1.,  0.],
       [-1.,  2., -1.],
       [ 0., -1.,  1.]])

In [12]:
evals,evecs = la.eig(A)

In [13]:
evals.real.round(15)

array([ 3.,  1., -0.])

In [14]:
np.round(np.real(evals),15)

array([ 3.,  1., -0.])

In [15]:
evecs

array([[-4.08248290e-01, -7.07106781e-01,  5.77350269e-01],
       [ 8.16496581e-01,  2.48915666e-16,  5.77350269e-01],
       [-4.08248290e-01,  7.07106781e-01,  5.77350269e-01]])