# MATH 210 Introduction to Mathematical Computing

**February 12, 2024**

In [1]:
import numpy as np

## NumPy Arrays

A NumPy array is like a vector or matrix. We can create an array using the NumPy function `np.array`.

In [2]:
v = np.array([1.,2.,3.])

In [3]:
v

array([1., 2., 3.])

Note that we enter values as floats with decimal `1.` since NumPy arrays have a defined type for their entries and most of our computations in this class with be with floating point numbers.

In [4]:
v.dtype

dtype('float64')

In general, a Python object is a bundle of data (called attributes) and functionality (called methods). A NumPy array is an object where the data are the entries but also we have data including datatype, dimension, size, and shape. And we have functionality such as `.sum`.

The vector `v` defined above is a 1-dimensiona array. It's like a list. It's not a row vector (a matrix with 1 row) or column vector (martix with 1 column). Access the number of dimensions with attribute `.ndim`.

In [5]:
v.ndim

1

In [6]:
v[1]

2.0

In [7]:
v.sum()

6.0

In [8]:
np.sum(v)

6.0

A matrix is a 2D array. Use the function `np.array` to create a matrix.

In [9]:
A = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])
A

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [10]:
N = 3
A = np.arange(1,N**2+1).reshape((N,N)).astype(np.float64)
A

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [11]:
A.ndim

2

In [12]:
A.shape

(3, 3)

In [13]:
A.size

9

In [14]:
A.dtype

dtype('float64')

In [15]:
A.T

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [16]:
np.transpose(A)

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [17]:
A.sum()

45.0

## Creating Arrays

The function `np.linspace(a,b,N)` creates the NumPy array of $N$ equally spaced (floating point) numbers from $a$ to $b$.

In [18]:
a = 0
b = 1
N = 5
x = np.linspace(a,b,N)
x

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

The function `np.arange(a,b,h)` creates the list of numbers from $a$ to $b$ (exclusive) incremented by $h$.

In [19]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

It's helpful to use `np.linspace` when we want to create a vector of values from `a` to `b` inclusively. And sometimes it's helpful to use `np.arange` when we want to specify the step size. But they are related. The function `np.linspace(a,b,N)` returns the list of number from `a` to `b` (inclusive) with step size:

$$
h = \frac{b - a}{N-1}
$$

Create a vector/matrix of zeros:

In [21]:
z = np.zeros(3)
z

array([0., 0., 0.])

In [22]:
z.dtype

dtype('float64')

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Create a vector/matrix of ones:

In [24]:
o = np.ones(5)
o

array([1., 1., 1., 1., 1.])

In [25]:
o.dtype

dtype('float64')

In [26]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Create the identiy matrix $I$:

In [27]:
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Create a diagonal matrix from a vector:

In [28]:
D = np.diag(np.arange(1,10)).astype(float)
D

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 4., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 5., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 6., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 7., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 9.]])

In [29]:
D.dtype

dtype('float64')

In [30]:
N = 5
A = -2*np.eye(N) + np.diag(np.ones(N-1),1) + np.diag(np.ones(N-1),-1)
A

array([[-2.,  1.,  0.,  0.,  0.],
       [ 1., -2.,  1.,  0.,  0.],
       [ 0.,  1., -2.,  1.,  0.],
       [ 0.,  0.,  1., -2.,  1.],
       [ 0.,  0.,  0.,  1., -2.]])

## Indexing and Slicing

Access entries in a NumPy array using index notation just like Python lists.

In [31]:
n = 5
A = np.arange(1,n**2+1).reshape((n,n)).astype(float)
A

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [32]:
A[1,3]

9.0

In [33]:
type(A[4,2])

numpy.float64

Access a row/column using colon `:`.

In [34]:
A[0,:]

array([1., 2., 3., 4., 5.])

In [35]:
A[:,1]

array([ 2.,  7., 12., 17., 22.])